spring.application.name=just-test-app
server.port = 8080
#server.address=localhost
app.host = localhost

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.drop-first=false
spring.liquibase.show-summary=verbose
spring.liquibase.user=app_user
spring.liquibase.url=jdbc:postgresql://postgres:5432/app_db
spring.liquibase.password=app_password
spring.liquibase.default-schema=fl

spring.datasource.url=jdbc:postgresql://postgres:5432/app_db
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.freemarker.charset=UTF-8
spring.freemarker.settings.number_format=0.##
spring.freemarker.settings.date_format=dd.MM.yyyy
spring.freemarker.cache=false

spring.security.user.name=user
spring.security.user.password=password

spring.freemarker.expose-request-attributes=true
spring.freemarker.settings.auto_include=spring.ftl

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG